[package]
authors = ["Isaac Cook <isaac@simpload.com>"]
name = "ngpool-rust"
version = "0.1.0"

[dependencies]
base64 = "0.7.0"
bitcoin = "0.10.1"
byteorder = "1.1.0"
hex = "0.2.0"
hyper = "0.11.6"
reqwest = "0.8.0"
rust-crypto = "0.2.36"
serde_json = "1.0.3"
